package com.github.alexandrepiveteau.parsers

/**
 * A convenience function for the [Parser.succeed] method, that lets you also specify the [value] that should be
 * produced by the created [Parser]. Internally, this simply maps a [Unit] [Parser.succeed] instance with the value you
 * provide.
 *
 * @param I The type of the input provided to the [Parser].
 * @param O The type of the output provided by the [Parser].
 * @param E The type of errors generated by the parser.
 *
 * @param value The value that should be offered by the [Parser] each time it is called.
 */
@ExperimentalParser
fun <I, O, E> Parser.Factory.succeedWith(value: O): Parser<I, O, E> =
        Parser.succeed<I, E>().map { value }